### PR TITLE
Update trackers list

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by duramato** [comment]
@quidsup i don't understand why it is adding `^M` characters, i downloaded the list from your site.

**Comment by jake-cryptic** [comment]
@quidsup @duramato I've had the same issue on my pull request #211

**Comment by quidsup** [comment]
Might be an issue with the editor?

**Comment by duramato** [comment]
I used GitHub's web editor to make the commit.

**Comment by games647** [comment]
It looks like the file contains windows line endings. As far as I know the upstream repository should only contain linux line endings. I thought the windows version of git does that automatically using core.autocrlf.

Tested with:
>file trackers.txt
trackers.txt: ASCII text, with CRLF, LF line terminators

You could convert it with dos2unix.

**Pull request closed without merging**
